# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/894feb17-1b0f-4f99-bdea-243a9000797b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9803-20BC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/hdd" =
    { device = "/dev/disk/by-uuid/01DA7D63A8DA6410";
      fsType = "ntfs3";
    };

  fileSystems."/mnt/windows" =
    { device = "/dev/disk/by-uuid/844CCCF54CCCE2D2";
      fsType = "ntfs3";
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/dab94e41-fe0c-4f1b-9e7a-5f51956dc221";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/97ade76b-daff-4704-81c0-d07a0885de73"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
