{ extraConfig, sharedConfig }: { pkgs, lib }: { ... } @ config: let extra = extraConfig { inherit pkgs; }; in lib.recursiveUpdate 
  (config // { 
    home = config.home // (with extra.hyprland; { 
	  packages = config.home.packages ++ [terminal fileManager menu];
	  file = config.home.file // {
	  	".config/hypr/hyprland.lua" = {
			text = ''
-- Generated by utils/withExtraConfig.nix
local terminal = "${lib.getExe terminal}"
local fileManager = "${lib.getExe fileManager}"
local menu = "${lib.getExe menu}"
local monitors = ${lib.generators.toLua {} monitors}
local autostartInWorkspace = ${lib.generators.toLua {} autostartInWorkspace}
-- End generated part

${builtins.readFile ../config/hypr/hyprland.lua}
			'';
		};
	  };
	}); 
  })
  sharedConfig
